name: Generate Snake Contribution Grid

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: Platane/snk@v2
        with:
          github_user_name: 'Manahil-04'
          outputs: 'github-contribution-grid-snake.svg'
