name: Generate Snake Animation

on:
  schedule:
    # Run at 12:00 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Generate the contribution snake
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Manahil-04
          outputs: dist/snake.svg

      # Push Snake to the output branch
      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
